name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3

      - name: Setup asv
        shell: bash -l {0}
        run: |
          conda install -c conda-forge asv --yes

      - name: Run benchmarks
        shell: bash -l {0}
        run: |
          asv machine --yes
          asv run 64f8f37..main --steps 5 --show-stderr --strict

      - name: Deploy on GH pages
        env:
          GITHUB_USER: ${{ github.actor }}
        shell: bash -l {0}
        run: |
          git config --global user.name $GITHUB_USER
          asv gh-pages --rewrite
